//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.06 at 11:45:30 PM EST 
//


package com.garmin.gwt.communicator.client.device;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for Device_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Device_t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Model" type="{http://www.garmin.com/xmlschemas/GarminDevice/v2}Model_t"/>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *         &lt;element name="RegistrationCode" type="{http://www.garmin.com/xmlschemas/GarminDevice/v2}RegistrationCode_t" minOccurs="0"/>
 *         &lt;element name="Unlock" type="{http://www.garmin.com/xmlschemas/GarminDevice/v2}UnlockCode_t" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DisplayName" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *         &lt;element name="MassStorageMode" type="{http://www.garmin.com/xmlschemas/GarminDevice/v2}MassStorageMode_t" minOccurs="0"/>
 *         &lt;element name="GarminMode" type="{http://www.garmin.com/xmlschemas/GarminDevice/v2}GarminMode_t" minOccurs="0"/>
 *         &lt;element name="Extensions" type="{http://www.garmin.com/xmlschemas/GarminDevice/v2}Extensions_t" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Device_t", propOrder = {
    "model",
    "id",
    "registrationCode",
    "unlock",
    "displayName",
    "massStorageMode",
    "garminMode",
    "extensions"
})
public class DeviceT {

    @XmlElement(name = "Model", required = true)
    protected ModelT model;
    @XmlElement(name = "Id")
    @XmlSchemaType(name = "unsignedInt")
    protected long id;
    @XmlElement(name = "RegistrationCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String registrationCode;
    @XmlElement(name = "Unlock")
    protected List<UnlockCodeT> unlock;
    @XmlElement(name = "DisplayName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String displayName;
    @XmlElement(name = "MassStorageMode")
    protected MassStorageModeT massStorageMode;
    @XmlElement(name = "GarminMode")
    protected GarminModeT garminMode;
    @XmlElement(name = "Extensions")
    protected ExtensionsT extensions;

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link ModelT }
     *     
     */
    public ModelT getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModelT }
     *     
     */
    public void setModel(ModelT value) {
        this.model = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the registrationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistrationCode() {
        return registrationCode;
    }

    /**
     * Sets the value of the registrationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistrationCode(String value) {
        this.registrationCode = value;
    }

    /**
     * Gets the value of the unlock property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the unlock property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUnlock().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UnlockCodeT }
     * 
     * 
     */
    public List<UnlockCodeT> getUnlock() {
        if (unlock == null) {
            unlock = new ArrayList<UnlockCodeT>();
        }
        return this.unlock;
    }

    /**
     * Gets the value of the displayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /**
     * Gets the value of the massStorageMode property.
     * 
     * @return
     *     possible object is
     *     {@link MassStorageModeT }
     *     
     */
    public MassStorageModeT getMassStorageMode() {
        return massStorageMode;
    }

    /**
     * Sets the value of the massStorageMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link MassStorageModeT }
     *     
     */
    public void setMassStorageMode(MassStorageModeT value) {
        this.massStorageMode = value;
    }

    /**
     * Gets the value of the garminMode property.
     * 
     * @return
     *     possible object is
     *     {@link GarminModeT }
     *     
     */
    public GarminModeT getGarminMode() {
        return garminMode;
    }

    /**
     * Sets the value of the garminMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link GarminModeT }
     *     
     */
    public void setGarminMode(GarminModeT value) {
        this.garminMode = value;
    }

    /**
     * Gets the value of the extensions property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionsT }
     *     
     */
    public ExtensionsT getExtensions() {
        return extensions;
    }

    /**
     * Sets the value of the extensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionsT }
     *     
     */
    public void setExtensions(ExtensionsT value) {
        this.extensions = value;
    }

}
