//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.06 at 11:45:30 PM EST 
//


package com.garmin.gwt.communicator.client.device;

/*
 * #%L
 * GWT Garmin API - Core API
 * %%
 * Copyright (C) 2012 - 2013 GWT Garmin API
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.garmin.gwt.communicator.client.device package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Device_QNAME = new QName("http://www.garmin.com/xmlschemas/GarminDevice/v2", "Device");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.garmin.gwt.communicator.client.device
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DeviceT }
     * 
     */
    public DeviceT createDeviceT() {
        return new DeviceT();
    }

    /**
     * Create an instance of {@link OutputFromUnitT }
     * 
     */
    public OutputFromUnitT createOutputFromUnitT() {
        return new OutputFromUnitT();
    }

    /**
     * Create an instance of {@link GarminModeT }
     * 
     */
    public GarminModeT createGarminModeT() {
        return new GarminModeT();
    }

    /**
     * Create an instance of {@link UpdateFileT }
     * 
     */
    public UpdateFileT createUpdateFileT() {
        return new UpdateFileT();
    }

    /**
     * Create an instance of {@link InputToUnitT }
     * 
     */
    public InputToUnitT createInputToUnitT() {
        return new InputToUnitT();
    }

    /**
     * Create an instance of {@link ProtocolsT }
     * 
     */
    public ProtocolsT createProtocolsT() {
        return new ProtocolsT();
    }

    /**
     * Create an instance of {@link ExtensionsT }
     * 
     */
    public ExtensionsT createExtensionsT() {
        return new ExtensionsT();
    }

    /**
     * Create an instance of {@link VersionT }
     * 
     */
    public VersionT createVersionT() {
        return new VersionT();
    }

    /**
     * Create an instance of {@link MassStorageModeT }
     * 
     */
    public MassStorageModeT createMassStorageModeT() {
        return new MassStorageModeT();
    }

    /**
     * Create an instance of {@link ModelT }
     * 
     */
    public ModelT createModelT() {
        return new ModelT();
    }

    /**
     * Create an instance of {@link AppProtocolT }
     * 
     */
    public AppProtocolT createAppProtocolT() {
        return new AppProtocolT();
    }

    /**
     * Create an instance of {@link LocationT }
     * 
     */
    public LocationT createLocationT() {
        return new LocationT();
    }

    /**
     * Create an instance of {@link FileT }
     * 
     */
    public FileT createFileT() {
        return new FileT();
    }

    /**
     * Create an instance of {@link MemoryRegionT }
     * 
     */
    public MemoryRegionT createMemoryRegionT() {
        return new MemoryRegionT();
    }

    /**
     * Create an instance of {@link UnlockCodeT }
     * 
     */
    public UnlockCodeT createUnlockCodeT() {
        return new UnlockCodeT();
    }

    /**
     * Create an instance of {@link ProtocolT }
     * 
     */
    public ProtocolT createProtocolT() {
        return new ProtocolT();
    }

    /**
     * Create an instance of {@link DataTypeT }
     * 
     */
    public DataTypeT createDataTypeT() {
        return new DataTypeT();
    }

    /**
     * Create an instance of {@link SpecificationT }
     * 
     */
    public SpecificationT createSpecificationT() {
        return new SpecificationT();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeviceT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.garmin.com/xmlschemas/GarminDevice/v2", name = "Device")
    public JAXBElement<DeviceT> createDevice(DeviceT value) {
        return new JAXBElement<DeviceT>(_Device_QNAME, DeviceT.class, null, value);
    }

}
