//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.06 at 11:45:30 PM EST 
//


package com.garmin.gwt.communicator.client.device;

/*
 * #%L
 * GWT Garmin API - Core API
 * %%
 * Copyright (C) 2012 - 2013 GWT Garmin API
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A list of supported protocols and associated data types. This list shows the features a pda supports.
 * 
 * <p>Java class for Protocols_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Protocols_t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Link" type="{http://www.garmin.com/xmlschemas/GarminDevice/v2}Protocol_t" minOccurs="0"/>
 *         &lt;element name="Application" type="{http://www.garmin.com/xmlschemas/GarminDevice/v2}AppProtocol_t" maxOccurs="unbounded"/>
 *         &lt;element name="Transport" type="{http://www.garmin.com/xmlschemas/GarminDevice/v2}Protocol_t" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Protocols_t", propOrder = {
    "links",
    "application",
    "transport"
})
public class ProtocolsT {

    @XmlElement(name = "Link")
    protected ProtocolT link;
    @XmlElement(name = "Application", required = true)
    protected List<AppProtocolT> application;
    @XmlElement(name = "Transport")
    protected ProtocolT transport;

    /**
     * Gets the value of the links property.
     * 
     * @return
     *     possible object is
     *     {@links ProtocolT }
     *     
     */
    public ProtocolT getLink() {
        return link;
    }

    /**
     * Sets the value of the links property.
     * 
     * @param value
     *     allowed object is
     *     {@links ProtocolT }
     *     
     */
    public void setLink(ProtocolT value) {
        this.link = value;
    }

    /**
     * Gets the value of the application property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the application property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getApplication().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@links AppProtocolT }
     * 
     * 
     */
    public List<AppProtocolT> getApplication() {
        if (application == null) {
            application = new ArrayList<AppProtocolT>();
        }
        return this.application;
    }

    /**
     * Gets the value of the transport property.
     * 
     * @return
     *     possible object is
     *     {@links ProtocolT }
     *     
     */
    public ProtocolT getTransport() {
        return transport;
    }

    /**
     * Sets the value of the transport property.
     * 
     * @param value
     *     allowed object is
     *     {@links ProtocolT }
     *     
     */
    public void setTransport(ProtocolT value) {
        this.transport = value;
    }

}
