//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.02.06 at 11:45:34 PM EST
//


package com.garmin.gwt.communicator.client.gpx;

/*
 * #%L
 * GWT Garmin API - Core API
 * %%
 * Copyright (C) 2012 - 2013 GWT Garmin API
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 	 Two lat/lon pairs defining the extent of an element.
 * 
 * 
 * <p>Java class for boundsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="boundsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="minlat" use="required" type="{http://www.topografix.com/GPX/1/1}latitudeType" />
 *       &lt;attribute name="minlon" use="required" type="{http://www.topografix.com/GPX/1/1}longitudeType" />
 *       &lt;attribute name="maxlat" use="required" type="{http://www.topografix.com/GPX/1/1}latitudeType" />
 *       &lt;attribute name="maxlon" use="required" type="{http://www.topografix.com/GPX/1/1}longitudeType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "boundsType")
public class BoundsType {

	@XmlAttribute(name = "minlat", required = true)
	protected double minlat;
	@XmlAttribute(name = "minlon", required = true)
	protected double minlon;
	@XmlAttribute(name = "maxlat", required = true)
	protected double maxlat;
	@XmlAttribute(name = "maxlon", required = true)
	protected double maxlon;

	/**
	 * Gets the value of the minlat property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link double }
	 * 
	 */
	public double getMinlat() {
		return minlat;
	}

	/**
	 * Sets the value of the minlat property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link double }
	 * 
	 */
	public void setMinlat(double value) {
		minlat = value;
	}

	/**
	 * Gets the value of the minlon property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link double }
	 * 
	 */
	public double getMinlon() {
		return minlon;
	}

	/**
	 * Sets the value of the minlon property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link double }
	 * 
	 */
	public void setMinlon(double value) {
		minlon = value;
	}

	/**
	 * Gets the value of the maxlat property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link double }
	 * 
	 */
	public double getMaxlat() {
		return maxlat;
	}

	/**
	 * Sets the value of the maxlat property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link double }
	 * 
	 */
	public void setMaxlat(double value) {
		maxlat = value;
	}

	/**
	 * Gets the value of the maxlon property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link double }
	 * 
	 */
	public double getMaxlon() {
		return maxlon;
	}

	/**
	 * Sets the value of the maxlon property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link double }
	 * 
	 */
	public void setMaxlon(double value) {
		maxlon = value;
	}

}
