//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.02.06 at 11:45:34 PM EST
//


package com.garmin.gwt.communicator.client.gpx;

/*
 * #%L
 * GWT Garmin API - Core API
 * %%
 * Copyright (C) 2012 - 2013 GWT Garmin API
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 * 	 A geographic point with optional elevation and time.  Available for use by other schemas.
 * 
 * 
 * <p>Java class for ptType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ptType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ele" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="time" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="lat" use="required" type="{http://www.topografix.com/GPX/1/1}latitudeType" />
 *       &lt;attribute name="lon" use="required" type="{http://www.topografix.com/GPX/1/1}longitudeType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ptType", propOrder = {
		"ele",
		"time"
})
public class PtType {

	@XmlSchemaType(name = "ele")
	protected double elevation;
	@XmlSchemaType(name = "dateTime")
	protected XMLGregorianCalendar time;
	@XmlAttribute(name = "lat", required = true)
	protected double latitude;
	@XmlAttribute(name = "lon", required = true)
	protected double longitude;

	/**
	 * Gets the value of the elevation property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link double }
	 * 
	 */
	public double getElevation() {
		return elevation;
	}

	/**
	 * Sets the value of the elevation property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link double }
	 * 
	 */
	public void setElevation(double value) {
		elevation = value;
	}

	/**
	 * Gets the value of the time property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getTime() {
		return time;
	}

	/**
	 * Sets the value of the time property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link XMLGregorianCalendar }
	 * 
	 */
	public void setTime(XMLGregorianCalendar value) {
		time = value;
	}

	/**
	 * Gets the value of the latitude property.
	 * 
	 * @return latitude
	 * 
	 */
	public double getLat() {
		return latitude;
	}

	/**
	 * Sets the value of the latitude property.
	 * 
	 * @param value latitude
	 */
	public void setLatitude(double value) {
		latitude = value;
	}

	/**
	 * Gets the value of the longitude property.
	 * 
	 * @return longitude
	 * 
	 */
	public double getLongitude() {
		return longitude;
	}

	/**
	 * Sets the value of the longitude property.
	 * 
	 * @param value longitude
	 * 
	 */
	public void setLongitude(double value) {
		longitude = value;
	}

}
